[id]
rule_focus_input  = '.element-container:has(#||configName||) + div[data-baseweb="select"] > div:focus-within'

[class]
rule_focus_input  = 'div[data-baseweb="select"] > div:focus-within'

[focus-border-colour]
rule_group = 'rule_focus_input'
rule_name  = ''
rule_type  = 'CustomRule_border-colour'

[focus-border-size]
rule_group = 'rule_focus_input'
rule_name  = ''
rule_type  = 'CustomRule_border-size'